### ISSUE TITLE
[Enhancement] Comprehensive support for asserting contents of lists/arrays

### ISSUE THREAD

**Issue by chipzoller** [kyverno/kuttl#23]
**What would you like to be added**:

A way to make an assertion that the contents of a field which is an array of objects or a list:

1. has the defined portion listed somewhere/anywhere
2. has the defined portion listed in the prescribed order

**Why is this needed**:

Kubernetes has loads of resources where arrays are components. In some cases, lists are unordered (like environment variables or Policy Report results) and in others the ordering is important (like initContainers). We need a way to specify how the assertion should be performed which entails stating "this entry must be present in the collection" versus "the collection must have all these entries and they must be in this exact order".

**Comment by chipzoller** [comment]
To provide some design proposal on the schema, imagine the first scenario in which a user wishes to assert that a given resource, which may have a field which is an array of strings or objects, has one or more results found somewhere within a designated portion of the resource.

Let's use a [Policy Report](https://kyverno.io/docs/policy-reports/) as an example of this. The PolicyReport and ClusterPolicyReport Custom Resources have a path `results[]` which is an array of objects. Each entry in the array is one result from a Kyverno rule decision. As a user, I want to assert that a ClusterPolicyReport exists and that the contents I provide in one specific path are found anywhere in the key.

Below, I'm asserting a ClusterPolicyReport and providing a partial array entry within `results[]`. It's partial because it's missing some fields that may be present in a final result, but a user wants to state, "the entry I list in `results[]` should be found anywhere within the `results[]` array and not necessarily just at index 0."

```yaml
apiVersion: wgpolicyk8s.io/v1alpha2
kind: ClusterPolicyReport
metadata:
  labels:
    app.kubernetes.io/managed-by: kyverno
  name: cpol-require-ns-labels
results:
- category: Best Practices
  message: 'validation error: The label `team` is required. rule check-for-ns-labels
    failed at path /metadata/labels/team/'
  policy: require-ns-labels
  resources:
  - apiVersion: v1
    kind: Namespace
    name: kube-node-lease
  result: fail
  rule: check-for-ns-labels
  scored: true
  severity: medium
  source: kyverno
```

One way this could be represented is like the below.

```yaml
apiVersion: kuttl.dev/v1beta1
kind: TestStep
assert_array:
  file: policyreport.yaml
  path: /results
  strategy: anywhere
```

Here, `assert-array` is a map and contains all the components required to make the decision:
* `file` points to a relative or full path to a YAML file to assert
* `path` points to the exact path within the `file` which should be checked against the cluster resource
* `strategy` allows the user to indicate whether what's in the `path` location in the `file` is found anywhere in the cluster resource. The value of `anywhere` means the contents should be found anywhere, and a value of `exact` means the contents should be asserted as written and in the exact order.
